modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="aegisesmod"
version="1.0.0"
displayName="Aegises Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="xxxsu, MCreator"
mixins = [
    "mixins.aegisesmod.json"
]

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.aegisesmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration